### PR TITLE
files: rename 'sftp' to 'ftp' as sftp is an ssh-based file transfer protocol

### PR DESCRIPTION
**Pull request by adamdecaf**
SFTP is a different protocol (that we also need to support), so let's
call the existing implementation what it is -- FTP.

Issue: #173

### CODE REVIEW

**Comment by wadearnold** [comment]
The ACH Rules require that any transmission of banking information, such as a customer’s bank account and routing number, be encrypted using “commercially reasonable” encryption technology if transmitted via an unsecured network, like the Internet. (This is similar to the PCI Requirement to use “Strong Cryptography” for transmission of cardholder data.)

**Comment by adamdecaf** [comment]
Do we need to explicitly disallow FTP without TLS then?

**Comment by wadearnold** [comment]
The only reason that I would keep FTP is if we want to keep it for testing/debugging.

**Comment by adamdecaf** [comment]
FTP can be secured (and would be called FTP(s)), but SFTP is a ssh-based protocol for transferring files. You've said banks would have FTP, but a customer of ours needs SFTP supported. 

- https://en.wikipedia.org/wiki/File_Transfer_Protocol
- https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol

**Pull request merged**
